### ISSUE TITLE
Application crash on going to a particular plugin 

### ISSUE THREAD

**Issue by DivyanshiSingh** [FNNDSC/ChRIS_store_ui#166] opened 2021-04-24 16:02 UTC
On routing to a particular plugins page, if the 'fetchRepoData' function fails the application is crashing.
![image](https://user-images.githubusercontent.com/53593872/115964968-90c32780-a544-11eb-9a19-4c418ccad9e1.png)

This error happened because the API (https://api.github.com/repos/${repo}) fails.
@jennydaman please check this, I can work on it.

**Comment by jennydaman** [comment] 2021-04-25 04:27
I will take a look at it.

Related to #161 so tagging @zrthxn

**Comment by jennydaman** [comment] 2021-04-25 05:40
@DivyanshiSingh can you provide more specific instructions on how to reproduce?

**Comment by DivyanshiSingh** [comment] 2021-04-25 06:36
Route to /plugins then choose any plugin listed, as soon as the plugins detail page loads, the application crashes

**Comment by jennydaman** [comment] 2021-04-25 06:50
Which branch, master or pf4? Have you tried `rm -rf node_modules && yarn`?

**Comment by zrthxn** [comment] 2021-04-25 07:31
Shouldn't happen on pf4 since this was something I knew about and I had fixed. I'll check it out again.

**Comment by DivyanshiSingh** [comment] 2021-04-25 07:47
@jennydaman its happening on pf4.
@zrthxn , if the fetch on https://api.github.com/repos/${repo} this url returns a 404 then the page will crash as repoData.license will be undefined and accessing the name will throw an error

**Comment by zrthxn** [comment] 2021-04-25 07:55
I have tested that already by blocking the URL and seeing the behaviour, and there is error handling there to prevent a crash. Maybe it's not working exactly as I expected. I'll fix it asap. Thanks.

**Comment by zrthxn** [comment] 2021-04-25 09:40
The issue existed before I had added exception handling but that was fixed in [ebba6a8](https://github.com/FNNDSC/ChRIS_store_ui/pull/161/commits/ebba6a8f29fefe6bbe8df3a89c1170dbb34a2ec7) and [4499243](https://github.com/FNNDSC/ChRIS_store_ui/pull/161/commits/4499243ec53da375fbeaeafa9da6415fef23d6e7). 

But after testing by blocking the URL so that the fetch call doesn't work, the app does not crash and just gives a notification. 
However if the fetch call has a **404 status**, it doesn't throw an error and so the app crashes because the error handling doesn't take over.

**Closed** 2021-04-25 14:06 UTC
Labels: bug
